### PR TITLE
Fix stdin and stderr handling during docker exec

### PR DESCRIPTION
**Pull request by stephanbuys**
@Joxit I tried to use your patch with a couple of non-trivial examples and came up with the following fixes, for your consideration.

### CODE REVIEW

**Comment by Joxit** [comment]
Thx for your contribution, I will try this.

**Comment by Joxit** [comment]
Sorry, I broke your branch.
I've done a rebase of your commit on my branch with some changes and GitHub does not recognize your PR as merged.

**Comment by stephanbuys** [comment]
No worries, as long as the code was useful!

**Comment by Joxit** [comment]
Merged see softprops/shiplift#61

**Pull request closed without merging**
